[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn fastapi_server:app --host 0.0.0.0 --port $PORT"

